// SPDX-License-Identifier: GPL-3.0-or-later
/*! THE BUILT-IN THEMES, AS FILES — not as a table in this binary.

The operator's request (notes/brief-themeone.txt, verbatim): "we want to keep
the themes from the file system ... whenever there are no themes in the
expected obsidian theme folder we would write them out and use them from
there. no hardcoded themes in the source code."

So the colours live in `src-tauri/themes/<Name>/{manifest.json,theme.css}` —
ordinary theme directories in stock's own layout — and this module does the
one thing a binary still has to do: carry those bytes so the app can WRITE
them out on a vault that has no themes (ledger item 4). `include_str!` embeds
the asset; it does not re-declare it. The distinction is the whole point and
it is checkable: the assets are OUTSIDE `src-tauri/src` and `ui/`, so item 9's
`scripts/lint-themes.sh` can grep both trees for palette colour literals and
palette id tables and find none.

THE DEFAULT IS ANUPPUCCIN, NOT A "Default" ASSET (goal anudefault). An empty
or absent `cssTheme` paints AnuPpuccin (ui/main.js DEFAULT_THEME / effTheme),
which seeding below writes into every vault; there is no Default row in either
picker. `ui/style.css`'s own `:root` values remain the base every theme layers
over, and what paints if the AnuPpuccin dir is gone or refused.

THE BUILT-INS ARE THIRD-PARTY THEMES, VERBATIM (goal themes4, operator
2026-10-03: "replace 1984/Slate/Wasp" with Minimal, Material Gruvbox,
AnuPpuccin, Solarized). Each asset directory holds the upstream repository's
`manifest.json` and `theme.css` byte for byte, at a pinned commit — never
edited, never regenerated. `PINNED` in the test module below records the
upstream repo, commit and sha256 of every file, and a test fails the moment
an asset's bytes stop matching its pin (a "small local fix" to a vendored
theme is how a vendored theme silently becomes a fork). Licences and full
licence texts: THIRD-PARTY.md. The old in-house three (1984, Slate, Wasp,
generated by the retired `scripts/gen-builtin-themes.sh`) are no longer
shipped; a vault they were already seeded into keeps them — seeding never
deletes (see migrate.rs for the legacy rule).
*/

// `is_builtin` has no non-test caller until the settings pane marks its rows
// (item 7). An allow beats inventing a use for the compiler's benefit — and it
// is scoped to this file.
#![allow(dead_code)]

use std::fs;
use std::path::Path;
use std::sync::Mutex;

/// One shipped theme: the bytes of a real theme directory. `name` is BOTH the
/// directory name and the manifest's `name`, because `themefs::themes_scan`
/// (the oracle's predicate, measured from stock in recon T1/T7) lists a theme
/// only when those two agree.
pub struct BuiltinTheme {
    pub name: &'static str,
    pub manifest: &'static str,
    pub css: &'static str,
}

macro_rules! builtin {
    ($name:literal, $dir:literal) => {
        BuiltinTheme {
            name: $name,
            manifest: include_str!(concat!("../themes/", $dir, "/manifest.json")),
            css: include_str!(concat!("../themes/", $dir, "/theme.css")),
        }
    };
}

/// The themes this binary can seed. Order is the order they are written; the
/// scan sorts what it lists, so it is not user-visible.
///
/// THE ONE PLACE A THEME NAME MAY APPEAR IN CODE. The markers below are read by
/// `scripts/lint-themes.sh` (ledger item 9 / criterion 2), which refuses a theme
/// name anywhere else in `src-tauri/src` or `ui/`. The rows are allowed here —
/// and ONLY here — because each one names a FILE: `builtin!` expands to
/// `include_str!("../themes/<dir>/…")`, so the name is a path, not a value. The
/// lint proves that per row: the asset directory must exist and its manifest's
/// `name` must equal the row's name. The moment a row carried colours instead
/// of a path it would be the palette table again, under a new name.
// THEME ASSETS BEGIN
pub const BUILTIN_THEMES: &[BuiltinTheme] = &[
    builtin!("AnuPpuccin", "AnuPpuccin"),
    builtin!("Material Gruvbox", "Material Gruvbox"),
    builtin!("Minimal", "Minimal"),
    builtin!("Solarized", "Solarized"),
];
// THEME ASSETS END

/// Is `name` one of ours? (For the settings pane, to mark a row; it is NOT a
/// privileged load path — after seeding a built-in is an ordinary file on disk
/// with no second code path. The seeding step below does not consult it: it
/// iterates the assets it ships, which is the same list from the other side.)
pub fn is_builtin(name: &str) -> bool {
    BUILTIN_THEMES.iter().any(|t| t.name == name)
}

/* ============================ R3 — SEEDING ================================
The one thing in this app that writes into `.obsidian/themes/`. The scan
itself still creates NOTHING (T1/T3 RESULT 1: stock creates neither `themes/`
nor `snippets/`), so seeding is a separate, explicit boot step and it is named
as one, on stderr, every time it runs.

THE PREDICATE IS PER *FILE*, and that is the whole contract:

  write `<vault>/.obsidian/themes/<Name>/<file>` if and only if that path does
  not exist.

Read against C3's three legs, which is why it is a file and not a flag:

- *no `.obsidian/themes/`* -> every path is missing -> all four are written,
  and from that moment they are ordinary theme directories: scanned, listed,
  chosen, hot-reloaded and deleted through the same code a third-party theme
  takes. There is no second load path (DESIGN §4).
- *second boot* -> every path exists -> nothing is opened for writing, so
  bytes AND mtime are unchanged. `create_dir_all` is not even called: it
  would be a no-op on the bytes but this way the directory's own mtime is
  untouchable too.
- *one deleted* -> exactly that one comes back. A global "have I seeded this
  vault" flag passes the first two legs and FAILS this one, which is why the
  state lives in the filesystem and nowhere else.

A USER EDIT SURVIVES, because an existing file is never opened. The cost of
that rule, stated plainly: a built-in the user deliberately deleted returns on
the next boot — the same thing stock does with a vault's config files, and the
direction that cannot lose bytes. An edit that makes the theme unlistable is
NOT repaired either; `themes_scan` already reports it with a reason (R6), and
guessing that a broken manifest was not meant would mean overwriting it.

`exists()` follows symlinks on purpose: a built-in the user has symlinked
somewhere else is present, so it is kept, not clobbered.
========================================================================== */

/// What one seeding pass did, per theme. Serialized to the UI for the
/// `[bseed:w<n>k<n>f<n>]` census token, so a gate phase can read the boot's
/// decision off the window title instead of trusting a log line.
#[derive(Debug, Default, Clone, serde::Serialize)]
pub struct SeedReport {
    /// themes that had at least one missing file, now written
    pub wrote: Vec<String>,
    /// themes already complete on disk — untouched, bytes and mtime
    pub kept: Vec<String>,
    /// `<name>: <io error>` — a vault we could not write to (read-only mount,
    /// a symlinked dir outside the landlock roots). Loud, never silent.
    pub failed: Vec<String>,
}

impl SeedReport {
    const fn empty() -> Self {
        SeedReport { wrote: Vec::new(), kept: Vec::new(), failed: Vec::new() }
    }
    /// the stderr line, and the shape the census token carries
    pub fn line(&self) -> String {
        format!(
            "[seed] themes: wrote {:?} kept {:?} failed {:?}",
            self.wrote, self.kept, self.failed
        )
    }
}

/// The last pass, for the census. One boot or one vault switch = one pass, so
/// this is the CURRENT root's report; a switch replaces it rather than
/// accumulating (the old vault's decision is not a fact about the new one).
static LAST_SEED: Mutex<SeedReport> = Mutex::new(SeedReport::empty());

/// Write the built-ins that are not already on disk. Returns what it did;
/// errors are collected, never propagated — a vault we cannot seed still
/// opens, and the scan then simply lists whatever IS there.
pub fn seed_builtin_themes(root: &Path) -> SeedReport {
    let td = root.join(".obsidian").join("themes");
    let mut rep = SeedReport::default();
    for t in BUILTIN_THEMES {
        let d = td.join(t.name);
        let files: [(&str, &str); 2] = [("manifest.json", t.manifest), ("theme.css", t.css)];
        let missing: Vec<&(&str, &str)> = files.iter().filter(|(f, _)| !d.join(f).exists()).collect();
        if missing.is_empty() {
            rep.kept.push(t.name.to_string());
            continue;
        }
        if let Err(e) = fs::create_dir_all(&d) {
            rep.failed.push(format!("{}: {e}", t.name));
            continue;
        }
        let mut err = None;
        for (f, bytes) in missing {
            if let Err(e) = fs::write(d.join(f), bytes) {
                err = Some(format!("{}/{f}: {e}", t.name));
                break;
            }
        }
        match err {
            Some(e) => rep.failed.push(e),
            None => rep.wrote.push(t.name.to_string()),
        }
    }
    rep
}

/// Seed `root` and record the pass for the census + the console. Called from
/// exactly two places (main.rs): the boot that opens the persisted/`VAULT_DIR`
/// vault, and `open_vault` (the vault switch and the freshly created vault).
pub fn seed_and_record(root: &Path) {
    let rep = seed_builtin_themes(root);
    eprintln!("{}", rep.line());
    if let Ok(mut g) = LAST_SEED.lock() {
        *g = rep;
    }
}

/// The recorded pass (empty before the first one: no vault open).
pub fn last_seed() -> SeedReport {
    LAST_SEED.lock().map(|g| (*g).clone()).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::themefs::{sanitize_css, themes_scan};
    use std::fs;
    use std::path::{Path, PathBuf};


    fn tmp_vault(tag: &str) -> PathBuf {
        let root =
            std::env::temp_dir().join(format!("opensidian-builtins-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join(".obsidian")).unwrap();
        root
    }

    /// write every shipped asset into `root`'s theme directory — through the
    /// PRODUCTION path (item 4), so the listing test below is an assertion
    /// about what the app actually puts on a user's disk, not about a copy of
    /// it written by the test.
    fn write_assets(root: &Path) {
        let rep = seed_builtin_themes(root);
        assert!(rep.failed.is_empty(), "seeding a tmp vault failed: {:?}", rep.failed);
    }

    /// THE criterion of ledger item 3 (C3's first leg): our OWN listing
    /// predicate — the one measured off stock — accepts every asset we ship.
    /// A built-in that the scan would exclude is a built-in the picker never
    /// shows, and the failure would only surface on a user's disk.
    #[test]
    fn builtin_assets_are_listed_by_themefs_own_predicate() {
        let root = tmp_vault("listed");
        write_assets(&root);
        let s = themes_scan(&root);
        let mut want: Vec<&str> = BUILTIN_THEMES.iter().map(|t| t.name).collect();
        want.sort();
        assert_eq!(s.listed, want, "every shipped asset must be LISTED");
        assert!(s.excluded.is_empty(), "no asset may be excluded: {:?}", s.excluded);
        assert_eq!(BUILTIN_THEMES.len(), 4, "non-vacuity: four built-ins ship");
    }

    /// The predicate's two halves, asserted directly so a failure says WHICH:
    /// the manifest parses as an object, and its `name` is the directory name.
    #[test]
    fn builtin_manifests_carry_stocks_shape_and_name_their_directory() {
        for t in BUILTIN_THEMES {
            let v: serde_json::Value = serde_json::from_str(t.manifest)
                .unwrap_or_else(|e| panic!("{}: manifest.json does not parse: {e}", t.name));
            let o = v.as_object().unwrap_or_else(|| panic!("{}: manifest is not an object", t.name));
            assert_eq!(
                o.get("name").and_then(|n| n.as_str()),
                Some(t.name),
                "{}: manifest name must equal the directory name",
                t.name
            );
            // stock's own theme manifests carry these (docs/fixtures/themefs/
            // vault-minimal/.obsidian/themes/Minimal/manifest.json)
            for k in ["version", "minAppVersion", "author"] {
                assert!(o.contains_key(k), "{}: manifest has no {k:?}", t.name);
            }
        }
    }

    /// A built-in takes the SAME path a third-party theme takes — because it
    /// IS one now — so it has to survive the same gate: our sanitizer must
    /// ACCEPT it (a refusal would make the built-in unlistable on a user's
    /// disk). Unlike the old in-house assets, upstream themes may carry
    /// `mask`/`-webkit-mask` declarations (Minimal and AnuPpuccin draw icons
    /// with them); stripping those is the loader's DEFINED behaviour for every
    /// theme (themefs::is_mask_prop, with a user-visible notice), so the
    /// count is reported, not forbidden. Editing the upstream CSS to make the
    /// count zero is exactly what `builtin_assets_are_the_pinned_upstream_bytes`
    /// forbids.
    #[test]
    fn builtin_css_is_accepted_by_our_own_sanitizer() {
        for t in BUILTIN_THEMES {
            let s = sanitize_css(t.css)
                .unwrap_or_else(|e| panic!("{}: a shipped built-in is refused: {e}", t.name));
            eprintln!("[builtins] {}: sanitized, {} mask declaration(s) stripped", t.name, s.stripped);
            assert!(!s.css.trim().is_empty(), "{}: sanitized to nothing", t.name);
        }
    }

    /* WHAT DIED HERE IN GOAL themes4, AND WHY (the rules fitted the old
       in-house, generated assets and are false for any real third-party theme):

         * `builtin_css_declares_on_body_not_on_root` — upstream themes declare
           on `.theme-dark`/`.theme-light`, `body`, `:root` and hundreds of
           component selectors; "two selectors, both on body" was a property of
           our generator, not of a theme.
         * `asset_values_are_wellformed_and_no_two_assets_share_one` and its
           `NON_COLOUR_TOKENS` allow-list (`--frame-width`, Wasp's frame) —
           "every custom property is a colour literal" and "no two built-ins
           share a colour" were checks that an EXTRACTION from ui/style.css did
           not cross a block boundary. There is no extraction any more.
         * `the_anchor_values_the_gate_phases_read_are_the_ones_the_assets_declare`
           — pinned smoke.sh's per-palette `--bg-base` pixel anchors. Those
           phases now read the theme's own `--background-primary` off the live
           body (computed style) and compare it to the painted pixel, so there
           is no literal on the harness side to drift from the asset.

       What is TRUE now, and checked instead: each asset is the pinned upstream
       file byte for byte (below), the listing predicate accepts it (above),
       the sanitizer accepts it (above), and it declares the stock names our
       chrome bridge and stock-default sheet are driven by (themefs.rs,
       `themefs_stockdef_builtins_drive_the_bridge_and_the_stock_defaults`). */

    /// (directory/manifest name, upstream repo, pinned commit,
    ///  sha256(manifest.json), sha256(theme.css)) — the bytes fetched from
    /// `https://raw.githubusercontent.com/<repo>/<commit>/<file>` on
    /// 2026-10-03 (goal themes4, progress.md records the fetch). A reviewer
    /// re-downloads those URLs and compares; this test makes the same
    /// comparison against what the binary actually embeds.
    const PINNED: &[(&str, &str, &str, &str, &str)] = &[
        (
            "AnuPpuccin",
            "anubisnekhet/AnuPpuccin",
            "82d207c646904e7af371ced499f682fbdfad1012",
            "5bcaf964520de9aaa128a66873951498913e6c254f162698cdafcb2bb732a5ba",
            "83ba4f6646f79bdc38920fd074c6734d7e6833f97184c0cb001f4eebef3231d7",
        ),
        (
            "Material Gruvbox",
            "alljavi/material_gruvbox_obsidian",
            "35b5bc1d7f857cecfc87bab4bfe74e3de11f4d11",
            "96781357c26bcdce6851d953a92d63e5e5e8e9a3564b7c2d03797dafb63ab24f",
            "45817b4d72e30251f62b23c8eb7de9b93792dc5a16122b3e78315fd46d5ededc",
        ),
        (
            "Minimal",
            "kepano/obsidian-minimal",
            "338a7274c7d3b84042207d70f512874b6af0a9d4",
            "22ca939102aa2eae4ad57b4d77933572bc055d4fee096b9bc00fd8e890680536",
            "8974d84fa5c6e6c82879eab5b0411bd57c7c868ea8beeab69d28b994657f7a5f",
        ),
        (
            "Solarized",
            "harmtemolder/obsidian-solarized",
            "11cc702755b912abcedbebb6328a32ffddc03eff",
            "aeb306ceaef793ed942cc9528994ffc46407d7df58bb4feeb01a44326533ae98",
            "f06663d358dfca2702da32302dc802c42a18b75629c4022ff4cd7dd57612845d",
        ),
    ];

    fn sha256_hex(b: &[u8]) -> String {
        use sha2::{Digest, Sha256};
        Sha256::digest(b).iter().map(|x| format!("{x:02x}")).collect()
    }

    /// VERBATIM: every embedded asset is the pinned upstream file, byte for
    /// byte, and the shipped set IS the pinned set (same names, same order).
    #[test]
    fn builtin_assets_are_the_pinned_upstream_bytes() {
        let shipped: Vec<&str> = BUILTIN_THEMES.iter().map(|t| t.name).collect();
        let pinned: Vec<&str> = PINNED.iter().map(|p| p.0).collect();
        assert_eq!(shipped, pinned, "every built-in has exactly one pin, and no pin is unshipped");
        for (t, (name, repo, commit, m_sha, c_sha)) in BUILTIN_THEMES.iter().zip(PINNED) {
            assert_eq!(t.name, *name);
            assert_eq!(
                sha256_hex(t.manifest.as_bytes()),
                *m_sha,
                "{name}/manifest.json is not github.com/{repo}@{commit} — vendored themes are never edited"
            );
            assert_eq!(
                sha256_hex(t.css.as_bytes()),
                *c_sha,
                "{name}/theme.css is not github.com/{repo}@{commit} — vendored themes are never edited"
            );
        }
        // the sha256 implementation itself, against the FIPS 180-2 vector, so
        // a broken digest cannot make every comparison above fail (or pass) together
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
    }

    /// The built-in Minimal and the cargo fixture installed by stock 1.13.7
    /// (tests/fixtures/themefs/Minimal, the bridge tests' input) are the SAME
    /// bytes — one upstream release, not two copies that can drift apart.
    #[test]
    fn builtin_minimal_is_byte_identical_to_the_stock_installed_fixture() {
        let m = BUILTIN_THEMES.iter().find(|t| t.name == "Minimal").expect("Minimal ships");
        assert_eq!(m.manifest, include_str!("../tests/fixtures/themefs/Minimal/manifest.json"));
        assert_eq!(m.css, include_str!("../tests/fixtures/themefs/Minimal/theme.css"));
    }

    // ================= ledger item 4 / criterion 3: SEEDING =================
    // The three legs C3 names, each as its own test, plus the two the
    // per-FILE predicate is there for (a partial dir, and an unwritable
    // vault). A reviewer runs: cargo test --manifest-path src-tauri/Cargo.toml
    // builtins:: -- --nocapture

    /// (bytes, mtime) of every file the seeder can write, so "unchanged" is a
    /// comparison and not a claim. Missing files are recorded as `None` —
    /// present in the map, so a file that VANISHED is a diff, not a silence.
    fn snapshot(root: &Path) -> Vec<(PathBuf, Option<(Vec<u8>, std::time::SystemTime)>)> {
        let td = root.join(".obsidian").join("themes");
        let mut out = Vec::new();
        for t in BUILTIN_THEMES {
            for f in ["manifest.json", "theme.css"] {
                let p = td.join(t.name).join(f);
                let v = fs::read(&p).ok().and_then(|b| {
                    fs::metadata(&p).and_then(|m| m.modified()).ok().map(|m| (b, m))
                });
                out.push((p, v));
            }
        }
        out
    }

    fn names(v: &[String]) -> Vec<&str> {
        v.iter().map(|s| s.as_str()).collect()
    }

    /// C3 LEG 1: a vault with no `.obsidian/themes/` gets the built-ins as
    /// REAL theme dirs, and the predicate that lists third-party themes lists
    /// them — the seeded bytes are the shipped bytes, so there is nothing
    /// "built-in" about them once they are down.
    #[test]
    fn seed_writes_the_builtins_when_the_themes_dir_is_absent() {
        let root = tmp_vault("absent");
        assert!(!root.join(".obsidian/themes").exists(), "precondition: no themes dir");
        let rep = seed_builtin_themes(&root);
        let mut want: Vec<&str> = BUILTIN_THEMES.iter().map(|t| t.name).collect();
        want.sort();
        let mut got = names(&rep.wrote);
        got.sort();
        assert_eq!(got, want, "every built-in is written on a vault that has none");
        assert!(rep.kept.is_empty() && rep.failed.is_empty(), "{rep:?}");
        let s = themes_scan(&root);
        assert_eq!(s.listed, want, "the seeded dirs must be LISTED by themefs's predicate");
        assert!(s.excluded.is_empty(), "{:?}", s.excluded);
        // the bytes on disk ARE the shipped asset, byte for byte
        for t in BUILTIN_THEMES {
            let d = root.join(".obsidian/themes").join(t.name);
            assert_eq!(fs::read_to_string(d.join("manifest.json")).unwrap(), t.manifest);
            assert_eq!(fs::read_to_string(d.join("theme.css")).unwrap(), t.css);
        }
    }

    /// C3 LEG 2: a second boot writes NOTHING — same bytes, same mtime, and
    /// the report says `kept`, which is the decision the census publishes.
    /// (mtime equality on a filesystem with coarse timestamps could hide a
    /// rewrite; that is why `seed_never_overwrites_a_user_edit` exists — an
    /// edit is detectable whatever the clock resolution.)
    #[test]
    fn seed_twice_touches_neither_bytes_nor_mtime() {
        let root = tmp_vault("twice");
        seed_builtin_themes(&root);
        let before = snapshot(&root);
        assert!(before.iter().all(|(_, v)| v.is_some()), "first pass left a file unwritten");
        let rep = seed_builtin_themes(&root);
        assert!(rep.wrote.is_empty(), "a second boot wrote {:?}", rep.wrote);
        assert_eq!(rep.kept.len(), BUILTIN_THEMES.len(), "{rep:?}");
        assert_eq!(snapshot(&root), before, "a second boot changed bytes or mtime");
    }

    /// The rule that makes leg 2 worth anything: an existing file is never
    /// opened, so a user's edit to a built-in survives every later boot.
    #[test]
    fn seed_never_overwrites_a_user_edit() {
        let root = tmp_vault("edit");
        seed_builtin_themes(&root);
        let p = root.join(".obsidian/themes/Solarized/theme.css");
        let edited = format!("{}\nbody.theme-dark {{ --text-normal: #ff00ff; }}\n", BUILTIN_THEMES[3].css);
        assert_eq!(BUILTIN_THEMES[3].name, "Solarized", "index/name drift");
        fs::write(&p, &edited).unwrap();
        let rep = seed_builtin_themes(&root);
        assert!(rep.wrote.is_empty(), "the edit was overwritten: {rep:?}");
        assert_eq!(fs::read_to_string(&p).unwrap(), edited, "the user's bytes must survive");
    }

    /// C3 LEG 3: delete ONE and the next boot restores exactly that one. This
    /// is the leg a global "already seeded this vault" flag fails, and the
    /// reason the state is the filesystem.
    #[test]
    fn seed_restores_only_the_theme_that_was_deleted() {
        let root = tmp_vault("deleted");
        seed_builtin_themes(&root);
        let gone = BUILTIN_THEMES[1].name; // Material Gruvbox — a name with a SPACE, the path case the old three never exercised
        fs::remove_dir_all(root.join(".obsidian/themes").join(gone)).unwrap();
        let others = snapshot(&root)
            .into_iter()
            .filter(|(p, _)| !p.starts_with(root.join(".obsidian/themes").join(gone)))
            .collect::<Vec<_>>();
        let rep = seed_builtin_themes(&root);
        assert_eq!(names(&rep.wrote), vec![gone], "only the deleted one is restored");
        assert_eq!(rep.kept.len(), BUILTIN_THEMES.len() - 1, "{rep:?}");
        let after = snapshot(&root)
            .into_iter()
            .filter(|(p, _)| !p.starts_with(root.join(".obsidian/themes").join(gone)))
            .collect::<Vec<_>>();
        assert_eq!(after, others, "restoring one theme touched another");
        let s = themes_scan(&root);
        assert!(s.listed.contains(&gone.to_string()), "restored but not listed: {:?}", s);
    }

    /// The predicate is per FILE, not per directory: a half-deleted built-in
    /// (the dir and one file survive) is completed, and the surviving file is
    /// not rewritten. A per-directory check would leave this vault with a
    /// theme `themes_scan` excludes for ever.
    #[test]
    fn seed_completes_a_half_deleted_theme_without_touching_its_sibling() {
        let root = tmp_vault("partial");
        seed_builtin_themes(&root);
        let d = root.join(".obsidian/themes").join(BUILTIN_THEMES[0].name);
        fs::remove_file(d.join("theme.css")).unwrap();
        let m_before = fs::metadata(d.join("manifest.json")).unwrap().modified().unwrap();
        assert!(!themes_scan(&root).excluded.is_empty(), "precondition: the half theme is excluded");
        let rep = seed_builtin_themes(&root);
        assert_eq!(names(&rep.wrote), vec![BUILTIN_THEMES[0].name], "{rep:?}");
        assert_eq!(fs::read_to_string(d.join("theme.css")).unwrap(), BUILTIN_THEMES[0].css);
        assert_eq!(
            fs::metadata(d.join("manifest.json")).unwrap().modified().unwrap(),
            m_before,
            "the sibling file was rewritten"
        );
        assert!(themes_scan(&root).excluded.is_empty(), "still excluded after completion");
    }

    /// A vault we cannot write to must OPEN anyway: the failure is collected
    /// and reported (the census's `f<n>`), never panicked, never silent. The
    /// unwritable case is forced the only portable way — a regular FILE where
    /// the themes directory belongs, which is also a real user's typo.
    #[test]
    fn seed_reports_an_unwritable_vault_instead_of_panicking() {
        let root = tmp_vault("unwritable");
        fs::write(root.join(".obsidian").join("themes"), b"not a directory\n").unwrap();
        let rep = seed_builtin_themes(&root);
        assert!(rep.wrote.is_empty() && rep.kept.is_empty(), "{rep:?}");
        assert_eq!(rep.failed.len(), BUILTIN_THEMES.len(), "every theme must report: {rep:?}");
        for f in &rep.failed {
            assert!(f.contains(':'), "a failure names the theme and the error: {f:?}");
        }
        assert!(rep.line().contains("failed ["), "the console line carries the failures");
        assert_eq!(themes_scan(&root).listed.len(), 0, "nothing was listed, and nothing crashed");
    }
}
