// SPDX-License-Identifier: GPL-3.0-or-later
// CENSUS TOKEN REGISTRY (goal gatetrain, G2). Loaded BEFORE main.js.
// Every rebase used to conflict on the ONE long census expression in
// updateTitle(): two branches each appending a token to the same line.
// A NEW token registers here instead — ONE self-contained line per token:
//   CENSUS.push(() => myTok());          // <feature>: what it proves
// The function is looked up when updateTitle() runs (never at load), so it may
// name anything main.js defines. Return "" for "absent", else " [name:...]".
// .gitattributes sets `merge=union` on THIS file: two branches that each add a
// line merge/rebase to BOTH lines, never a conflict. The price of union: edit
// or delete a line on two branches at once and both versions survive — so
// lines here are append-only; change a token by changing the function it calls.
// Tokens are appended AFTER every inline token (end of the title), in this
// file's line order; a token that throws is published as [cerr:<index>].
var CENSUS = [];
CENSUS.push(() => { const L = CMDS.filter(c => c.id === "editor:toggle-bullet-list" || c.id === "editor:toggle-numbered-list"); return " [lt:" + L.length + "/" + L.filter(c => !c.when || c.when()).length + "]"; });   // listtoggle: both list commands registered / offered by the palette (editing view only)
CENSUS.push(() => sgeoTok());   // setcenter R3: settings modal geometry [sbox:] [snav:] [srow1:] [shkf:] [shkc:] [shk1/2:] (only while settings is open)
CENSUS.push(() => Ed.rvTaskTok());   // rvtask R5: reading-view task boxes [rvtask:n/checked] + painted centres per source line [rvtaskxy:]
CENSUS.push(() => foldTok());   // collapseall R7: [fold:fe<c>/<n>:<C|E>,bm<c>/<n>:<C|E>] fold state of both trees, read off the DOM
CENSUS.push(() => caSync());   // collapseall R3/R4: [fecab:x0-x1,y][bmcab:x0-x1,y] painted rects of the two header toggles
CENSUS.push(() => sidePane === "bm" ? " [bmvis:" + bmVisRows().length + "]" : "");   // collapseall: bookmark rows NOT folded away (what is seen)
CENSUS.push(() => { const q = s => document.querySelector(s), b = e => e ? getComputedStyle(e).backgroundColor.replace(/\s+/g, "") : "-", vis = e => !!e && e.getClientRects().length > 0, o = ["mbox=" + b(q("#mbox")), "lgpop=" + b(q("#main .lgpop:not([hidden])") || q("#main .lgpop")), "sbox=" + b(q("#sbox")), "ac=" + b(q("#main .ac:not([hidden])") || q("#main .ac")), "rnbox=" + b(q("#rnbox"))]; for (const [n, s] of [["pcard", "#pcard"], ["ulcard", "#ulcard"], ["delcard", "#delcard"], ["bmecard", "#bmecard"], ["findbar", ".findbar"]]) { const e = [...document.querySelectorAll(s)].find(vis); if (e) o.push(n + "=" + b(e)); } return " [ovl:" + o.join("|") + "]"; });   // overlaytheme R4: resolved background of every --bg-elevated floating surface (mbox=palette+switcher, lgpop=graph options, sbox=settings, ac, rnbox always; other cards when open) — proves Layer 3 repaints under a vault theme
CENSUS.push(() => { const q = s => document.querySelector(s), b = e => e ? getComputedStyle(e).backgroundColor.replace(/\s+/g, "") : "-", vis = e => !!e && e.getClientRects().length > 0, o = ["mbox=" + b(q("#mbox")), "lgpop=" + b(q("#main .lgpop:not([hidden])") || q("#main .lgpop")), "sbox=" + b(q("#sbox")), "ac=" + b(q("#main .ac:not([hidden])") || q("#main .ac")), "rnbox=" + b(q("#rnbox"))]; for (const [n, s] of [["pcard", "#pcard"], ["ulcard", "#ulcard"], ["delcard", "#delcard"], ["bmecard", "#bmecard"], ["findbar", ".findbar"]]) { const e = [...document.querySelectorAll(s)].find(vis); if (e) o.push(n + "=" + b(e)); } if (vis(q("#main .lgpop:not([hidden])"))) o.push("lgopen=1"); const g = [...document.querySelectorAll("#main .lggear")].find(vis); if (g) { const r = g.getBoundingClientRect(); o.push("gear=" + Math.round(r.x + r.width / 2) + "," + Math.round(r.y + r.height / 2)); } return " [ovl:" + o.join("|") + "]"; });   // overlaytheme R4: resolved background of every --bg-elevated floating surface (mbox=palette+switcher, lgpop=graph options, sbox=settings, ac, rnbox always; other cards when open; lgopen=1 + gear=x,y so a phase can open graph options without fixed coords) — proves Layer 3 repaints under a vault theme
CENSUS.push(() => bmAddTok());   // bmactive: [modal:bmadd] [bmadd:<note>|<group>|<title>|<opts>] [bmax:<title;chooser;cancel;save;x>] [bmafocus:] — the group menu's "Add bookmark" modal (docs/recon-bmactive F1)
CENSUS.push(() => wsTok());          // wsrestore (R28): [wstabs:] every tab+mode of every group, [ws:writes,restored,dropped]
CENSUS.push(() => " [rtabs:" + [...document.querySelectorAll("#rtabs > button.stab[id^='rtab-']")].map(b => b.id.slice(5)).join("|") + "]");   // wsrestore R20.3: the right tab strip in DOM order, always bl|out|tags|toc (content panes only; a stored sidebar graph/localgraph leaf is preserved in the file, never rendered)
CENSUS.push(() => $("picker").hidden ? "" : " [precent:" + [...document.querySelectorAll("#p-recent li span")].map(s => s.textContent.replace(/[[\]|]/g, "")).join("|") + "]");   // brand (goal opensidian): the vault picker's recent rows (full paths) while it shows — proves the migrated vault list
CENSUS.push(() => tjTok());   // tocjump: the outline's own note leaf [tj:<note>|top:|car:|st:|ae:] read even while a graph/other pane is focused
CENSUS.push(() => tjxyTok());   // tocjump: painted click points [tjxy:] — outline rows by line, each pane's active tab + content corner, an empty explorer point
CENSUS.push(() => { const P = document.querySelector("#main .pane.focused") || document.querySelector("#main .pane"), vis = e => !!e && e.getClientRects().length > 0, tcol = s => { const m = (s || "").match(/[\d.]+/g) || []; return m.length >= 3 && !(m.length > 3 && +m[3] === 0) ? m.slice(0, 3).map(v => Math.round(+v)).join(".") : ""; }, bg = e => { for (let x = e; x && x.nodeType === 1; x = x.parentElement) { const c = tcol(getComputedStyle(x).backgroundColor); if (c) return c; } return "-"; }, rc = r => [r.x, r.y, r.width, r.height].map(Math.round).join(","), out = [], el = (n, e, ink) => { if (vis(e)) out.push(n + "=" + rc(e.getBoundingClientRect()) + ":" + (ink ? tcol(getComputedStyle(e).color) : bg(e))); }, txt = (n, root, s) => { if (!root) return null; const w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); for (let t; (t = w.nextNode());) { const i = t.data.indexOf(s); if (i >= 0) { const g = document.createRange(); g.setStart(t, i); g.setEnd(t, i + s.length); out.push(n + "=" + rc(g.getBoundingClientRect()) + ":" + tcol(getComputedStyle(t.parentElement).color)); return t.parentElement; } } return null; }; const lp = P && P.querySelector(".lp"); el("body", lp); const pt = txt("text", lp, "Plain paragraph text"); txt("h1", lp, "Audit heading"); el("link", lp && lp.querySelector(".wl"), 1); el("side", $("side")); el("treeact", document.querySelector("#tree .trow.active")); el("treetext", document.querySelector("#tree .trow.note:not(.active)"), 1); el("ribbon", $("ribbon")); el("tabstrip", P && P.querySelector(".tabbar")); el("tabact", P && P.querySelector(".tab.active")); el("tabtext", P && P.querySelector(".tab.active"), 1); el("title", $("wframe")); const st = [...document.querySelectorAll(".status")].find(vis); el("status", st); el("stattext", st, 1); el("pal", $("mbox")); el("palsel", [...document.querySelectorAll("#mlist .mrow.sel")].find(vis)); el("button", $("del-no")); if (pt) out.push("sel=" + (tcol(getComputedStyle(pt, "::selection").backgroundColor) || "-")); return " [tlr:" + out.join("|") + "]"; });   // themelight: per audited REGION its painted rect (x,y,w,h, CSS px) + resolved colour (bg walked up to the first opaque ancestor; ink for text/link/tabtext/treetext/stattext) — the audit samples pixels at these rects, phase themelight asserts these colours against the stock audit
CENSUS.push(() => { const P = document.querySelector("#main .pane.focused") || document.querySelector("#main .pane"), vis = e => !!e && e.getClientRects().length > 0, tcol = s => { const m = (s || "").match(/[\d.]+/g) || []; return m.length >= 3 && !(m.length > 3 && +m[3] === 0) ? m.slice(0, 3).map(v => Math.round(+v)).join(".") : ""; }, bg = e => { for (let x = e; x && x.nodeType === 1; x = x.parentElement) { const c = tcol(getComputedStyle(x).backgroundColor); if (c) return c; } return "-"; }, rc = r => [r.x, r.y, r.width, r.height].map(Math.round).join(","), out = [], el = (n, e, ink) => { if (vis(e)) out.push(n + "=" + rc(e.getBoundingClientRect()) + ":" + (ink ? tcol(getComputedStyle(e).color) : bg(e))); }, txt = (n, root, s) => { if (!root) return null; const w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); for (let t; (t = w.nextNode());) { const i = t.data.indexOf(s); if (i >= 0) { const g = document.createRange(); g.setStart(t, i); g.setEnd(t, i + s.length); out.push(n + "=" + rc(g.getBoundingClientRect()) + ":" + tcol(getComputedStyle(t.parentElement).color)); return t.parentElement; } } return null; }; const lp = P && P.querySelector(".lp"); el("body", lp); const pt = txt("text", lp, "Plain paragraph text"); txt("h1", lp, "Audit heading"); el("link", lp && lp.querySelector(".wl"), 1); el("side", $("side")); el("treeact", document.querySelector("#tree .trow.active")); el("treetext", document.querySelector("#tree .trow.note:not(.active)"), 1); el("ribbon", $("ribbon")); el("tabstrip", P && P.querySelector(".tabbar")); el("tabact", P && P.querySelector(".tab.active")); el("tabtext", P && P.querySelector(".tab.active"), 1); el("title", $("wframe")); const st = [...document.querySelectorAll(".status")].find(vis); el("status", st); el("stattext", st, 1); el("pal", $("mbox")); el("palsel", [...document.querySelectorAll("#mlist .mrow.sel")].find(vis)); el("button", $("del-no")); el("extlink", lp && lp.querySelector(".lt"), 1); const tg = lp && lp.querySelector(".tag"); el("tag", tg, 1); el("tagbg", tg); el("check", lp && lp.querySelector("input[type=checkbox]:checked")); el("toggle", [...document.querySelectorAll(".sctl.toggle.on")].find(vis)); el("primary", [...document.querySelectorAll(".sbtn.acc")].find(vis)); const fe = document.activeElement; if (fe && fe.id === "hkfilter" && vis(fe)) { const r = fe.getBoundingClientRect(); out.push("focus=" + [r.x - 4, r.y - 4, r.width + 8, r.height + 8].map(Math.round).join(",") + ":" + bg(fe)); } if (pt) out.push("sel=" + (tcol(getComputedStyle(pt, "::selection").backgroundColor) || "-")); return " [tlr:" + out.join("|") + "]"; });   // themelight: per audited REGION its painted rect (x,y,w,h, CSS px) + resolved colour (bg walked up to the first opaque ancestor; ink for text/link/tabtext/treetext/stattext) — the audit samples pixels at these rects, phase themelight asserts these colours against the stock audit
CENSUS.push(() => { const P = document.querySelector("#main .pane.focused") || document.querySelector("#main .pane"), vis = e => !!e && e.getClientRects().length > 0, tcol = s => { const m = (s || "").match(/[\d.]+/g) || []; return m.length >= 3 && !(m.length > 3 && +m[3] === 0) ? m.slice(0, 3).map(v => Math.round(+v)).join(".") : ""; }, bg = e => { for (let x = e; x && x.nodeType === 1; x = x.parentElement) { const c = tcol(getComputedStyle(x).backgroundColor); if (c) return c; } return "-"; }, rc = r => [r.x, r.y, r.width, r.height].map(Math.round).join(","), out = [], el = (n, e, ink) => { if (vis(e)) out.push(n + "=" + rc(e.getBoundingClientRect()) + ":" + (ink ? tcol(getComputedStyle(e).color) : bg(e))); }, txt = (n, root, s) => { if (!root) return null; const w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); for (let t; (t = w.nextNode());) { const i = t.data.indexOf(s); if (i >= 0) { const g = document.createRange(); g.setStart(t, i); g.setEnd(t, i + s.length); out.push(n + "=" + rc(g.getBoundingClientRect()) + ":" + tcol(getComputedStyle(t.parentElement).color)); return t.parentElement; } } return null; }; const lp = P && P.querySelector(".lp"); el("body", lp); const pt = txt("text", lp, "Plain paragraph text"); txt("h1", lp, "Audit heading"); el("link", lp && lp.querySelector(".wl"), 1); el("side", $("side")); el("treeact", document.querySelector("#tree .trow.active")); el("treetext", document.querySelector("#tree .trow.note:not(.active)"), 1); el("ribbon", $("ribbon")); el("tabstrip", P && P.querySelector(".tabbar")); el("tabact", P && P.querySelector(".tab.active")); el("tabtext", P && P.querySelector(".tab.active"), 1); el("title", $("wframe")); const st = [...document.querySelectorAll(".status")].find(vis); el("status", st); el("stattext", st, 1); el("pal", $("mbox")); el("palsel", [...document.querySelectorAll("#mlist .mrow.sel")].find(vis)); el("button", $("del-no")); el("extlink", lp && lp.querySelector(".lt"), 1); const tg = lp && lp.querySelector(".tag"); el("tag", tg, 1); el("tagbg", tg); el("check", lp && lp.querySelector("input[type=checkbox]:checked")); el("toggle", [...document.querySelectorAll(".sctl.toggle.on")].find(vis)); el("primary", [...document.querySelectorAll(".sbtn.acc")].find(vis)); const fe = $("hkfilter"); if (vis(fe)) { const r = fe.getBoundingClientRect(); out.push("focus=" + [r.x - 4, r.y - 4, r.width + 8, r.height + 8].map(Math.round).join(",") + ":" + bg(fe)); } if (pt) out.push("sel=" + (tcol(getComputedStyle(pt, "::selection").backgroundColor) || "-")); return " [tlr:" + out.join("|") + "]"; });   // themelight: per audited REGION its painted rect (x,y,w,h, CSS px) + resolved colour (bg walked up to the first opaque ancestor; ink for text/link/tabtext/treetext/stattext) — the audit samples pixels at these rects, phase themelight asserts these colours against the stock audit
CENSUS.push(() => llTok());   // listlinks: [lstl:k=v,...] reading-view list/link geometry of the listlinks fixture (docs/listlinks/recon.md REQ-n), only while that fixture is read
CENSUS.push(() => nobTok());   // stock-name goal, criterion 3: [nob:] every rendered text node + human attribute + settings/command tables, hits of the stock app name (literal config-dir path allowed; test-only, OPENSIDIAN_NOBPROBE=1); [nobxy:] [nobnav:] click points
CENSUS.push(() => vargTok());   // vaultarg: [vault:<open vault, full path|->] + [vargerr:<reason>] while a rejected `opensidian <arg>` reason is on screen (docs/vaultarg/README.md §5)
